#! /bin/sh

usage() {
    echo `basename $0`": Search Google Scholar from the commandline."
    echo "  Enter search terms just like with the pubmed command."
    echo "  The mozilla browser is used by default, unless the BROWSER"
    echo "  environment variable is set to name firefox, netscape, or"
    echo "  konqueror."
    echo 
    echo "Options:"
    echo "   -lynx   Use the lynx browser in your terminal window."
    echo "   "
    echo ""
    echo "See also home page at http://www.nada.kth.se/~arve/biblio."
}

BROWSER=${BIBLIO_BROWSER:-mozilla}

# Should we use biblio?
if [ "$1" = "-lynx" ]; then
    BROWSER='lynx';
    shift
fi

# Check that we have at least one param
if [ -z $1 ]; then
  echo "Error: You provided no search terms"
  echo
  usage
  exit
fi

URL=`echo "http://scholar.google.com/scholar?q="$*|sed s/\ /+/g`
echo $URL

case $BROWSER in
    (mozilla|firefox|netscape) $BROWSER -remote "openURL("$URL")";;
    (konqueror)                konqueror $URL;;
    (lynx)                     lynx $URL
esac

